### ISSUE TITLE
Pull request comment can not be deleted

### ISSUE THREAD

**Issue by Meloyg** [izhangzhihao/delete-comment#39]
![image](https://github.com/izhangzhihao/delete-comment/assets/62586556/53ad6c12-c173-411e-a88e-03d424785529)

I tried to delete the comment from the Amplify bot with your GitHub actions, but it didn't work at all.

my yml file
```
name: delete comments from open-collective-bot
on:
  workflow_dispatch:
jobs:
  delete-comments:
    runs-on: ubuntu-latest
    steps:
      - uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: aws-amplify-ap-southeast-2[bot]
          issue_number: ${{ github.event.number }} # remove comments from the current PR

```
