### ISSUE TITLE
More debug output

### ISSUE THREAD

**Issue by koppor** [izhangzhihao/delete-comment#43]
I have

```yaml
      - name: Remove all comments by "github-actions[bot]"
        uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ steps.read-pr_number.outputs.pr_number }}
```

Output of action:

```
 ##[debug]Loading env
Run izhangzhihao/delete-comment@master
starting process for JabRef/jabref
##[debug]Node Action run completed with exit code 0
```

I would assume the following comment was removed:

![Image](https://github.com/user-attachments/assets/145e558b-aed8-4198-96a2-288625507263)

But it did not.

Thus, I would like to have some way of debug.

`core.debug` offers debbugging

`ACTIONS_STEP_DEBUG` `true` secreat

See https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging

Refs https://github.com/izhangzhihao/delete-comment/issues/39
